/* Real UI handlers with mocked HTTP: no server, LLM, or GPU jobs. */
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const elements=new Map(),sent=[];
function element(id){if(!elements.has(id))elements.set(id,{value:'',textContent:'',options:[],addEventListener(){},replaceChildren(...items){this.options=items;},add(item){this.options.push(item);}});return elements.get(id);}
const state={boot:{surprise_style_lock:true},connection:{model:'test'},settings:{runtime:{backend:'torch'},lora:{path:'',strength:1,auto_trigger:true}}};
const context=vm.createContext({state,$:element,Option:function(text,value){this.text=text;this.value=value;},save(){},toast(){},busy:async(id,fn)=>fn(),pollSurprises:async()=>{},openRunner(){throw Error('unexpected');},api:async(url,data)=>{
 if(url==='/api/loras')return {folder:'local',loras:[{path:'local/test.safetensors',name:'Test'}],rejected:[]};
 if(url==='/api/loras/inspect')return {path:data.path,trigger_word:'test_sound'};
 if(url==='/api/surprises'){sent.push(JSON.parse(JSON.stringify(data)));return {};}
 throw Error(url);
}});
vm.runInContext(fs.readFileSync('src/yue2_studio/static/loras.js','utf8'),context);
const app=fs.readFileSync('src/yue2_studio/static/app.js','utf8');
vm.runInContext(app.slice(app.indexOf('function bindSurprise()'),app.indexOf('async function pollSurprises()')),context);
(async()=>{
 vm.runInContext('bindLoras();bindSurprise()',context);
 await vm.runInContext('refreshLoras()',context);
 assert.equal(element('surpriseLoraSelect').options.length,2);
 element('surpriseLoraSelect').value='local/test.safetensors';element('surpriseLoraSelect').onchange();
 assert.equal(element('loraSelect').value,'local/test.safetensors');
 element('loraStrength').value='0.75';element('loraStrength').oninput();
 assert.match(element('surpriseLoraStatus').textContent,/0.75/);
 element('surpriseCount').value='2';
 assert.equal(element('surpriseLockStyle').checked,true);
 await assert.rejects(element('surpriseButton').onclick(),/Enter a style/);
 element('surpriseStyle').value='Exact rock style';
 await element('surpriseButton').onclick();
 assert.equal(sent[0].lock_style,true);
 assert.equal(sent[0].style,'Exact rock style');
 element('surpriseLockStyle').checked=false;
 assert.equal(sent[0].settings.lora.path,'local/test.safetensors');
 assert.equal(sent[0].settings.lora.strength,.75);
 assert.equal(sent[0].settings.lora.auto_trigger,true);
 element('surpriseLoraSelect').value='';element('surpriseLoraSelect').onchange();
 await element('surpriseButton').onclick();
 assert.equal(sent[1].settings.lora.path,'');
 assert.equal(sent[1].lock_style,false);
 assert.equal(sent[0].settings.lora.path,'local/test.safetensors','previous submission unchanged');
 element('loraSelect').value='local/test.safetensors';element('loraSelect').onchange();
 assert.equal(element('surpriseLoraSelect').value,'local/test.safetensors');
 state.settings.runtime.backend='audio.cpp';vm.runInContext('syncLoras()',context);
 assert.match(element('surpriseLoraStatus').textContent,/requires Torch/);
 const html=fs.readFileSync('src/yue2_studio/static/index.html','utf8');
 for(const id of ['surpriseLoraSelect','surpriseLoraHelp','surpriseLoraStatus','refreshSurpriseLoras'])assert(html.includes('id="'+id+'"'));
 assert.equal((html.match(/id="surpriseLoraSelect"/g)||[]).length,1);
 console.log('Surprise LoRA passed: catalogue, two-way sync, strength, request payload, None, GGUF notice.');
 const originalApi=context.api;
 context.api=async(url,data)=>url==='/api/loras/inspect'?{path:data.path,training_style:'Saved training style'}:originalApi(url,data);
 state.settings.runtime.backend='torch';
 element('style').value='';element('surpriseStyle').value='';
 element('surpriseLoraSelect').value='local/test.safetensors';
 await element('surpriseLoraSelect').onchange();
 assert.equal(element('style').value,'Saved training style');
 assert.equal(element('surpriseStyle').value,'Saved training style');
 let approve;
 context.confirmReplace=(title,message,fn)=>{approve=fn;};
 element('style').value='My main edit';element('surpriseStyle').value='My surprise edit';
 await element('surpriseLoraSelect').onchange();
 assert.equal(element('style').value,'My main edit','confirmation required');
 assert.equal(element('surpriseStyle').value,'My surprise edit');
 element('style').value='Newer edit while dialog open';approve();
 assert.equal(element('style').value,'Newer edit while dialog open');
 assert.equal(element('surpriseStyle').value,'Saved training style');
 await vm.runInContext('refreshLoras()',context);
 assert.equal(element('style').value,'Newer edit while dialog open','refresh does not autofill');
 context.api=async(url,data)=>url==='/api/loras/inspect'?{path:data.path}:originalApi(url,data);
 await element('surpriseLoraSelect').onchange();
 assert.equal(element('style').value,'Newer edit while dialog open','legacy metadata leaves text unchanged');
 console.log('Training style passed: both boxes, replacement confirmation, in-flight edits, refresh and legacy safety.');
})().catch(error=>{console.error(error);process.exitCode=1;});
